CREATE TABLE IF NOT EXISTS mpa_rating
(
    rating_id   BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    CONSTRAINT mpa_rating_pk PRIMARY KEY (rating_id)
);
CREATE TABLE IF NOT EXISTS films
(
    film_id       BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR NOT NULL,
    description   VARCHAR(200),
    release_date  DATE,
    duration      Integer,
    mpa_rating_id BIGINT,
    CONSTRAINT films_pk PRIMARY KEY (film_id),
    CONSTRAINT films_fk FOREIGN KEY (mpa_rating_id) REFERENCES mpa_rating (rating_id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS genre
(
    genre_id   BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    CONSTRAINT genre_pk PRIMARY KEY (genre_id)
);
CREATE TABLE IF NOT EXISTS users
(
    user_id       BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR,
    email    VARCHAR NOT NULL,
    login    VARCHAR NOT NULL,
    birthday DATE,
    CONSTRAINT users_pk PRIMARY KEY (user_id)
);
CREATE TABLE IF NOT EXISTS genre_id
(
    id       BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT genre_id_pk PRIMARY KEY (id),
    CONSTRAINT genre_id_fk FOREIGN KEY (genre_id) REFERENCES genre (genre_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT genre_id_fk_1 FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS friends
(
    friends_id        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id   BIGINT  NOT NULL,
    friend_id BIGINT  NOT NULL,
    status    BOOLEAN NOT NULL,
    CONSTRAINT friends_pk PRIMARY KEY (FRIENDS_ID),
    CONSTRAINT friends_id_fk FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS film_like
(
    like_id      BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT like_id_pk PRIMARY KEY (like_id),
    CONSTRAINT film_id_fk FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE ON UPDATE CASCADE
);